
<?php

$str = filter_var($_POST['str'], FILTER_VALIDATE_FLOAT);
if (is_numeric($str)) {
    $digits = str_split($str); // Преобразование строки в массив
    $sum = array_sum($digits); // Сума елементов массива
    echo "Вы ввели: " . $_POST["str"] . "<br>";
    echo " Сумма числел {$str} = {$sum}";
}
else {
    echo "Неверный ввод";
}


?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <form name="authForm" method="POST" action="">
        <input type="text" name="str">
        <input type="submit">
    </form>
</body>
</html>



